### ISSUE TITLE
Is it possible to generate heightmaps from normalmaps with Heman?

### ISSUE THREAD

**Issue by jdolan** [prideout/heman#7]
Hi,

I was wondering if it is possible to use Heman "in the other direction" and infer height from normals? I have a whole mess of normalmaps, and I'd like to implement parallax mapping for them in my game engine. Programmatically generating the heightmaps in my asset pipeline would be a massive timesaver.

If it's not already possible, do you have thoughts on how difficult would it be to add this functionality, based on what's already there? I'd consider taking a crack at it myself.

Thanks!

**Comment by prideout** [comment]
Hi Jay, this feature does not exist in Heman but I don't think it would be terribly difficult to implement.  From the normal map you can calculate two sets of derivatives (nx/nz and ny/nz), then do two sweeps to produce the height map (one horizontal, one vertical).  During the sweeps you maintain a "current elevation" value, adding the derivatives to it as you march along, and stamping down the values into the height map.  Asking an LLM for help might be useful.

**Comment by jdolan** [comment]
Thanks, Phil! You're spot-on. ChatGPT was able to spit out some reasonably correct looking code for exactly this approach. Your description helped. I'm going to give it a whirl. Cheers!
